apiVersion: v1
kind: Pod
metadata:
  name: time-machine
  labels:
    app: time-machine
spec:
  containers:
    - name: time-machine
      image: time-machine
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
